name: CI/CD

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 22.15.0
        uses: actions/setup-node@v3
        with:
          node-version: '22.15.0'

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3 libsqlite3-dev

      - name: Install dependencies
        run: npm ci

      - name: Rebuild better-sqlite3 from source
        run: npm rebuild better-sqlite3 --build-from-source --verbose

      - name: Build bundle with ncc
        run: npx ncc build src/index.ts -m -o dist

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
